services:
  - type: web
    name: aletheia-news-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn aletheia_news_proxy:app --host 0.0.0.0 --port 10000
